### ISSUE TITLE
`recur` special form doesn't work inside match expressions

### ISSUE THREAD

**Issue by missingfaktor** [missingfaktor/akar#11]
Here is an example:

``` clojure
akar.try-out=> (defn tail-recursive-sum [x running-total]
                 (match x
                        0  running-total
                        :_ (recur (dec x) (+ running-total x))))

CompilerException java.lang.IllegalArgumentException: Mismatched argument count to recur, expected: 0 args, got: 2, compiling:(/private/var/folders/cl/wrqg78nx3c3cxwyb4nmmv1l8394zzh/T/form-init6487640578328843470.clj:4:13)
```

Easy to see why this is happening. Akar expands clause bodies to anonymous functions, and `recur` binds to the nearest closing function.

**Comment by BrunoBonacci** [comment]
Hi @missingfaktor,

Yes, this is the problem I was referring to during your last talk.
which is a common issue in platforms which do not support "Generalised TCO".
Mundane recursion here wouldn't work as it will cause StackOverflow on large numbers

`(tail-recursive-sum 1000000)`

If you find a way to get around this I would be curious to see your solution.
Great work with Akar, anyway.

Bruno

**Comment by missingfaktor** [comment]
Thanks, @BrunoBonacci!

I investigated this a bit... It appears `recur` is not equipped to span across nested functions. I am not certain if it is even possible in general at all. 😢 This will be harder to fix than I already imagined it would be...

**Comment by BrunoBonacci** [comment]
as mentioned earlier JVM doesn't support "Generalised TCO" (https://en.wikipedia.org/wiki/Tail_call). It is possible, but quite hard when the platform underneath doesn't support. You can close this ticket if you don't intend work on it, anyway it is a common issue with pattern matching libraries in Clojure.

**Comment by missingfaktor** [comment]
I am well aware of JVM's limitations in this regard. 

Clojure's `recur` works reasonably well for many use cases still, and it would have been nice if we could figure out a way to make it work inside `match`  expressions too. So far I have nothing.

**Comment by missingfaktor** [comment]
A fellow contributor @rahulkavale pointed out that `trampoline` could be used as a workaround. 

``` clojure
(defn tail-recursive-sum [x running-total]
  (match x
         0  running-total
         :_ #(tail-recursive-sum (dec x) (+ running-total x))))

(alter-var-root #'tail-recursive-sum (fn [cur] (partial trampoline cur)))

(tail-recursive-sum 1000 0)
```

**Comment by BrunoBonacci** [comment]
Very interesting workaround.

**Comment by missingfaktor** [comment]
Superseded by #14.
