### ISSUE TITLE
Migrate to clojure.spec

### ISSUE THREAD

**Issue by missingfaktor** [missingfaktor/akar#12]
`clojure.spec` appears to cover much the same grounds as seqex, and it's part of the standard library. We should migrate out syntax layer to use `clojure.spec`.

**Comment by missingfaktor** [comment]
Assigned to @rahulkavale.

**Comment by missingfaktor** [comment]
@rahulkavale Check out [this blog post](http://blog.klipse.tech/clojure/2016/10/10/defn-args.html) on how to write macros with `core.spec`. (And the one that follows it.)

**Comment by missingfaktor** [comment]
Also, I would want to avoid a big bang refactoring for this. 

I propose creating another namespace `akar.syntax-next`, and reimplementing parts, one by one, in a bottom up fashion. You could start with boolean literals for example. One commit per syntax rule would be ideal. 

Once we have ported over all of the supported syntax, and have tests to support this assertion, we can get rid of `akar.syntax`, and rename `akar.syntax-next` to `akar.syntax`.

**Comment by rahulkavale** [comment]
@missingfaktor makes sense
