### ISSUE TITLE
Snapshot release

### ISSUE THREAD

**Issue by darkleaf** [missingfaktor/akar#19]
Can you create SNAPSHOT release with last features?

**Comment by missingfaktor** [comment]
Thanks for your interest, @darkleaf! We are planning to make a proper release - 0.2.0 - very soon. :-)

**Comment by darkleaf** [comment]
thanks

**Comment by missingfaktor** [comment]
What are you using Akar for? We will be interested in hearing your experiences!

**Comment by darkleaf** [comment]
Ok. I started to use Akar yesterday. I need match clojure.spec problems to human readable messages. I know about solutions like https://github.com/alexanderkiel/phrase. But I need more complex cases. I want to match by spec name or spec predicate. The one possible way to do thit is pattern matching.

Draft is here: https://github.com/darkleaf/publicator/commit/2ea0798268c4b99c4877127daaf114431240d9c0

**Comment by missingfaktor** [comment]
I published v0.2.0 today.
