### ISSUE TITLE
ClojureScript release

### ISSUE THREAD

**Issue by missingfaktor** [missingfaktor/akar#9]
Assigned to @rahulkavale.

**Comment by missingfaktor** [comment]
@rahulkavale mentioned he has been unable to find any time for this, and the situation is unlikely to change in near future. We are closing this issue for now. We will reopen it when we have someone who could take it up.

**Comment by viebel** [comment]
@missingfaktor @rahulkavale I'd love to work on porting to `cljs` and self-host `cljs` (I'm the author of KLIPSE).

It shouldn't be so hard except the fact that `seqex` hasn't been ported to `cljs`. But maybe we don't need it anymore - now that we have `clojure.spec` in clojure and clojurescript. 

See https://github.com/jclaggett/seqex/issues/9

**Comment by missingfaktor** [comment]
@viebel Thank you for volunteering! We have porting to `clojure.spec` on our radar. Let's take up the CLJS release task once that is done. I will try to finish that up soon.

**Comment by missingfaktor** [comment]
Blocked by #12.
